### ISSUE TITLE
🐛 [Bug] 타임라인에서 게시물이 중복되어 보인다

### ISSUE THREAD

**Issue by dorrion** [Co-Run-Toy-Project/costagram#121]
## Description

POST 요청 후 타임라인에서 게시물이 2개가 보이는 현상이 발생하고 있습니다.
서버 로그를 확인해봤을 때 한 번 스크롤 내릴 때 page가 1 -> 3 이렇게 변하는 걸 볼 수 있어서 원인이 아닐까 생각합니당! 확인 바랍니다!

![image](https://user-images.githubusercontent.com/100553086/219667063-f0874959-dea6-4452-9dce-42c0694fd79f.png)

### DB에서는 게시물이 1개로 확인이 됩니다
![image](https://user-images.githubusercontent.com/100553086/219666158-48346c5c-5d6b-4fe3-92a0-a536e0449248.png)

### 타임라인에서 중복으로 보입니다
- 총 게시물이 1개인데 2개가 보이는 상황
![image](https://user-images.githubusercontent.com/100553086/219666054-7ff68bd0-c4d2-49fa-b59c-641cf9c83c33.png)

- 총 게시물이 3개인데 게시물이 모두 중복돼서 중복된 두가지 게시물만 보이는 상황
![image](https://user-images.githubusercontent.com/100553086/219669577-9357ffb1-d142-40fe-8d8d-f591ad68c961.png)

## ETC
- 주의 사항 혹은 기타 내용

**Comment by yeowool1010** [comment]
post는 문제가 없는데 무한스크롤 구현에서 발생한 에러였습니다! 코드 수정했고 머지 진행하겠습니다~!
